package com.xy1m.model.reference.types;

public enum CampaignOnAirReason {
    CAMPAIGN_ON_AIRCAMPAIGN_DISABLED,
    CAMPAIGN_FLY_DATES_PAST,
    CAMPAIGN_FLY_DATES_FUTURE,
    CAMPAIGN_DAILY_CAPPED,
    CAMPAIGN_DAILY_CAPPED_MONTHLY,
    CAMPAIGN_DAILY_CAPPED_CAMPAIGN,
    CAMPAIGN_BUDGET_DEPLETED,
    CAMPAIGN_ALL_PROMOTED_LINKS_DISABLED,
    CAMPAIGN_ALL_PROMOTED_LINKS_REJECTED,
    ALL_PROMOTED_LINKS_EXPIRED,
    ALL_PROMOTED_LINKS_PENDING,
    WAITING_FOR_START_HOUR,
    NO_RUNNING_PROMOTED_LINKS,
    MISSING_BILLING_INFO,
    EXPIRED_BILLING_INFO,
    FAILED_BILLING_INFO,
    BAD_CONTENT,
    OUTSTANDING_UNPAID_BALANCE,
    TOS_VIOLATION,
    NEW_CUSTOMER_PENDING,
    PAUSED,
    MARKED_DELETED,
    LEGACY_UNKNOWN,
    FAILED_THRESHOLD_BILLING,
    CAMPAIGN_NOT_IN_SCHEDULING_HOURS
}
